### ISSUE TITLE
Maybe transfer the repo to @components

### ISSUE THREAD

**Issue by rogeriopradoj** [SamMousa/datatables#3]
Hi, @SamMousa , maybe would be a good idea transfer this repo to @components.

I think they would maintain you as the official maintaner, and, as a good point, the repo could have more visibility (what should have the updates by the community via Pull Requests be more frequent).

What do you say?

Thanks!

**Comment by holtkamp** [comment]
What is the status of this? Both Composer and Packagist.org are suggesting to use (non existing) `bower-asset/datatables` instead of this `components/datatables` package, why would that be?

https://packagist.org/packages/components/datatables

**Comment by SamMousa** [comment]
Yes, I have deprecated this package.
Checkout https://github.com/francoispluchino/composer-asset-plugin

This is a plugin that allows you to use bower and npm assets.
These are package managers for javascript.

The advantage of this approach is that there is no need for a composer.json in javascript libraries. Most javascript libraries have a bower.json for bower or package.json for npm.

**Comment by holtkamp** [comment]
Thanks for the swift response, seems an elegant solution indeed.

It might be useful to include that pointer to your README.MD ;)

**Comment by SamMousa** [comment]
Done!
